[defaults]
llm-ollama-model = "hf.co/unsloth/Devstral-Small-2507-GGUF:Q4_K_M"
llm-ollama-host = "http://pc.local:11434"
asr-wyoming-ip = "192.168.1.143"
tts-wyoming-ip = "192.168.1.143"
tts-kokoro-host = "http://pc.local:8880/v1"
tts-kokoro-voice = "af_bella(1)+af_nicole(1.5)"
wake-server-ip = "192.168.1.143"
input-device-name = "logitech,airpods,macbook"
output-device-name = "iloud,airpods,dell,macbook"

[transcribe]
extra-instructions = """
Assume the user is often discussing Python programming.
Use backticks for variable names, function names, and other code elements.
Follow PEP8: use `snake_case` for variables, functions, and package names; `CamelCase` for classes.
Other frequent words are `pipefunc` (or `PipeFunc`), IonQ (a quantum computing company), trapped-ion quantum computer, `pre-commit`, `pytest`, `ruff`, `unidep`.
My name is Bas Nijholt.
"""
